language: python
python:
  - "3.8"

services: 
  - docker
before_install:
  - docker-compose up -d
script:
#   - docker-compose run django cd /SOM_PROJECT && ls
#   - docker-compose run django ls
  - docker-compose run django bash -c "service mongodb start && python manage.py makemigrations && python manage.py migrate && python ./SOM_PROJECT/manage.py test -k"
