services: 
  - docker
before_install:
  - docker-compose up
script:
#   - docker-compose run django cd /SOM_PROJECT && ls
#   - docker-compose run django ls
  - docker-compose run django python ./SOM_PROJECT/manage.py test -k som
