language: python # language
python: # python version
  - "3.6"
  - "3.7"
  - "3.8"
# services: 
#   - mongodb
env: # environment
  -DJANGO=2.2 
  matrix:
  - MONGODB=4.2.6
install: # package
  - pip install -r requirements.txt
#   - sudo apt-get install mongodb
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=${MONGODB} mongodb-org-server=${MONGODB} mongodb-org-shell=${MONGODB} mongodb-org-mongos=${MONGODB} mongodb-org-tools=${MONGODB} --allow-downgrades
  - sudo service mongod start
  - sudo service mongod status
before_script: # => 6
#   - sleep 15
#   - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script: # => 7
  - python manage.py test
