language: python # language
    python: # python version
      - "3.6"
      - "3.7"
      - "3.8"
    services: # DB we use nosql
      - mongodb
    env: # environment
      -DJANGO=2.2 DB=mongodb
    install: # package
      - pip install -r requirements.txt

    script: # => 7
      - python manage.py test
