language: python # language
python: # python version
  - "3.6"
  - "3.7"
  - "3.8"

env: # environment
  -DJANGO=2.2 DB=mongodb
install: # package
  - pip install -r requirements.txt
  - sudo apt-get install mongodb
  - sudo service mongodb start
  - sudo service mongodb status
before_script: # => 6
#   - sleep 15
#   - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script: # => 7
  - python manage.py test
