version: "3.1"



services:
  django:
    build: .
    ports:
      - "8080:8080"    
#     command: bash -c "service mongodb start && python manage.py makemigrations && python manage.py migrate && echo 'now running django'"
    
      
