# Generated by Django 2.2.5 on 2021-04-12 11:44

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataframe',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('file_name', models.CharField(default='2021-04-12 11:44:37.591165', max_length=200)),
                ('time', models.DateField(auto_now=True)),
                ('data', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
